In [2]:
import os
print("현재 사용 중인 환경 경로:")
!conda env list

현재 사용 중인 환경 경로:

# conda environments:
#
# * -> active
# + -> frozen
base                     C:\Users\everh\miniconda3
dl_env               *   C:\Users\everh\miniconda3\envs\dl_env
base                     C:\Users\everh\miniconda3
dl_env               *   C:\Users\everh\miniconda3\envs\dl_env



In [4]:
import torch
import pandas as pd
import numpy as np

# 1. 버전 확인
print(f"1. PyTorch 버전: {torch.__version__}")

# 2. 텐서 생성 테스트 (딥러닝의 기본 단위)
# 2x3 크기의 랜덤 숫자가 담긴 행렬을 만듭니다.
x = torch.rand(2, 3)
print("\n2. 생성된 테스트 텐서:\n", x)

# 3. 간단한 행렬 연산
y = x + 10
print("\n3. 연산 결과 (모든 요소에 10 더하기):\n", y)

# 4. 데이터 분석 라이브러리 확인
df = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
print("\n4. Pandas 데이터프레임 생성 성공:\n", df)

print("\n✨ 모든 환경이 완벽하게 준비되었습니다! 열공하세요! ✨")

1. PyTorch 버전: 2.10.0+cpu

2. 생성된 테스트 텐서:
 tensor([[0.5131, 0.5730, 0.6198],
        [0.3426, 0.9870, 0.5978]])

3. 연산 결과 (모든 요소에 10 더하기):
 tensor([[10.5131, 10.5730, 10.6198],
        [10.3426, 10.9870, 10.5978]])

4. Pandas 데이터프레임 생성 성공:
    A  B
0  1  2
1  3  4

✨ 모든 환경이 완벽하게 준비되었습니다! 열공하세요! ✨


In [5]:
import torch
import pandas as pd
import numpy as np

# 1. 버전 확인
print(f"1. PyTorch 버전: {torch.__version__}")

# 2. 텐서 생성 테스트 (딥러닝의 기본 단위)
# 2x3 크기의 랜덤 숫자가 담긴 행렬을 만듭니다.
x = torch.rand(2, 3)
print("\n2. 생성된 테스트 텐서:\n", x)

# 3. 간단한 행렬 연산
y = x + 10
print("\n3. 연산 결과 (모든 요소에 10 더하기):\n", y)

# 4. 데이터 분석 라이브러리 확인
df = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
print("\n4. Pandas 데이터프레임 생성 성공:\n", df)

print("\n✨ 모든 환경이 완벽하게 준비되었습니다! 열공하세요! ✨")

1. PyTorch 버전: 2.10.0+cpu

2. 생성된 테스트 텐서:
 tensor([[0.8023, 0.8126, 0.6498],
        [0.0343, 0.2752, 0.4625]])

3. 연산 결과 (모든 요소에 10 더하기):
 tensor([[10.8023, 10.8126, 10.6498],
        [10.0343, 10.2752, 10.4625]])

4. Pandas 데이터프레임 생성 성공:
    A  B
0  1  2
1  3  4

✨ 모든 환경이 완벽하게 준비되었습니다! 열공하세요! ✨


In [6]:
import torch

# 1. 0으로 가득 찬 텐서 만들기 (3행 3열)
zeros = torch.zeros(3, 3)

# 2. 랜덤한 숫자로 가득 찬 텐서 만들기
random_box = torch.rand(3, 3)

# 3. 두 텐서 더하기
result = zeros + random_box

print("--- 딥러닝의 기본 단위 '텐서' 테스트 ---")
print(result)
print("\n축하합니다! 이제 딥러닝 수식을 코드로 구현할 준비가 되었습니다.")

--- 딥러닝의 기본 단위 '텐서' 테스트 ---
tensor([[6.5798e-04, 8.4924e-01, 8.3736e-01],
        [1.9881e-01, 8.5935e-01, 7.8854e-01],
        [7.5515e-01, 3.7911e-01, 2.0321e-01]])

축하합니다! 이제 딥러닝 수식을 코드로 구현할 준비가 되었습니다.
